name: limpar

on:
  push:
    branches: [ "main" ] # Executa toda vez que você atualizar o código
  workflow_dispatch:      # Permite que você ative a compilação manualmente pelo celular


jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Limpar
     run: |
      make clean
